### PR TITLE
Add matrix multiplication network.

### PR DESCRIPTION
**Pull request by jgosmann**
Adds a matrix multiplication network based on PR nengo/nengo#431 orginally proposed by @youzak.

Input names are adhering to the new standard defined in nengo/nengo#887.

### CODE REVIEW

**Comment by tbekolay** [comment]
I haven't looked in great detail, but if the tests pass then this LGTM! Which reminds me, we should get TravisCI building this repo. I'll do that this afternoon.

Only thing I would request is that @youzak's name/email be added to the commit message.

**Comment by Seanny123** [comment]
LGTM. Like Trevor, I haven't done manual matrix multiplication in ages, so I don't totally understand the transform pattern, but the test assuages all of my fears.

**Comment by jgosmann** [comment]
> Only thing I would request is that @youzak's name/email be added to the commit message.

done :heavy_check_mark:

**Comment by tbekolay** [comment]
Cool cool, I'll run the tests and if they pass I'll merge :+1:

**Pull request merged**
