### PR TITLE
Fixed spasafe_names function to ignore additional non-SPA characters

### PR DESCRIPTION
**Pull request by xchoo**
Fixed spasafe_names function to ignore "-" and "'" characters in addition to the " " character.

### CODE REVIEW

**Comment by hunse** [comment]
I would probably replace the apostrophe with nothing, rather than an underscore. That way, something like ``"Eric's cat"`` becomes ``"ERICS_CAT"`` rather than ``"ERIC_S_CAT"``.

**Comment by jgosmann** [comment]
I did that and made the function more general, might reuse it in `nengo_spa` (I needed such a function before in a few cases). More details are in my commit message.

**Comment by hunse** [comment]
I'll merge.

**Comment by hunse** [comment]
Ok, this ended up being a bit more involved than I expected. @jgosmann, can you look over my changes, since they're mostly to the stuff that you wrote? I also added a bit of documentation. If it looks good, you can go ahead and merge.

**Comment by jgosmann** [comment]
Looks great to me! 🍰

**Pull request merged**
