### PR TITLE
WIP: Black box RNNs

### PR DESCRIPTION
**Pull request by tbekolay**
Still a WIP, but figured I would make the PR to demonstrate my use case, which is incorporating an RNN defined through some backend (Theano for now, but will probably use the hessian-free code from @drasmuss to do it in numpy / pycuda also) in Nengo through a Node.

I'll be using it for audio, but for testing I used a quick MNIST example; it processes each of the 28 rows of pixels one at a time to eventually make a classification decision. See [the rendered notebook](https://gist.github.com/tbekolay/44afef7a3a9e0d97afb8) for proof it works.

### CODE REVIEW

**Comment by studywolf** [comment]
This is really neat! 

So, when I was transferring one of the networks I learned with dan's HF library my code ended up just being 
```python
        # load up our network
        W = np.load('Controllers/rnn_weights/arm1_seed5.npz')['arr_0']
        np.random.seed(5) # same seed as training
        rnn = RNNet(shape=[4, 100, 100, 2], struc_damping=0.0,
                     layers=[Linear(), Tanh(), Tanh(), Linear()],
                     error_type="mse", debug=False,
                     rec_layers=[False, True, True, False],
                     conns={0:[1, 2], 1:[2], 2:[3]},
                     load_weights=W)

        node = nengo.Node(lambda x: rnn.step(x)[-1][1])
```
so having a helper function for that would be overkill, but I haven't tried running a Theano network for a single timestep and specifying the input before! 

For all the backend functions, would those become part of the repo too? I see there are a bunch of other helper functions, are they functions from the theano backend or specific to integrating with nengo?

**Comment by tbekolay** [comment]
Yeah, the intention is to generalize things so that regardless of what you're using under the hood (Dan's thing, Theano, whatever) the interface is the same. Right now it's just the one thing right now, so it's a matter of adding others and seeing what helper function are generally useful and what are backend specific.

And yeah, my use case is the super simple one, so if people think it's better off in another repo and only the processes are useful, that's fair too, either way works for me, just figured it'd reduce duplication if we amalgamate the DL stuff here.

**Comment by studywolf** [comment]
Makes sense!

Oh another use case popped up today I just wanted to mention (possibly here is not the right place!) , where there's some fancy structure going on in a network built NEF styles and then I want to do classification using the spiking output from the NEF network. That strikes me as potentially the most difficult integration of DL stuff and nengo.

**Comment by tbekolay** [comment]
This PR doesn't make sense for this repo anymore. If anyone's interested in doing audio stuff in Nengo, check out https://github.com/tbekolay/phd.

**Pull request closed without merging**
